name: Release

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      push_image: true 